apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chain-demo-sandbox
  namespace: chain-sandbox
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chain-demo-sandbox
  template:
    metadata:
      labels:
        app: chain-demo-sandbox
    spec:
      containers:
        - name: chain-demo-sandbox
          command: [ "/bin/bash" ]
          args: [ ""]
          image:  $REGISTRY/test:SNAPSHOT-$BUILD_NUMBER
          resources:
            requests:
              cpu: 1
              memory: 2Gi
            limits:
              cpu: 2
              memory: 4Gi
          volumeMounts:
            - name: data
              mountPath: /data/blocks
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1317
            - containerPort: 8545
            - containerPort: 26657
            - containerPort: 26656
          env:
            - name: TZ
              value: GMT
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - chain-demo-sandbox
              topologyKey: "kubernetes.io/hostname"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "my-storage-class"
        resources:
          requests:
            storage: 10Gi