apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME-node-0-production-testing
  namespace: chain-prd-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP_NAME-node-0-production-testing
  template:
    metadata:
      labels:
        app: $APP_NAME-node-0-production-testing
    spec:
      containers:
      - name: $APP_NAME-node-0-production-testing
        command: [ "/bin/bash" ]
        args: [ "-c","fetchd start  --json-rpc.api eth,txpool,personal,net,debug,web3,miner --api.enable true --minimum-gas-prices 0.0001afet  --home /data/blocks/fetchd/node0  --rpc.laddr tcp://0.0.0.0:26657" ]
        image:  $REGISTRY/$APP_NAME:SNAPSHOT-$BUILD_NUMBER
        resources:
          requests:
            cpu: 0.1
            memory: 0.5Gi
          limits:
            cpu: 2
            memory: 1Gi
        volumeMounts:
        - name: host-time
          mountPath: /etc/localtime
        - name: data
          mountPath: /data/blocks
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 1317
          - containerPort: 8545
          - containerPort: 26657
          - containerPort: 26656
        env:
          - name: TZ
            value: GMT
      volumes:
      - name: host-time
        hostPath:
          path: /etc/localtime
      - name: data
        persistentVolumeClaim:
          claimName: fetchchain-ssd-pvc-0
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - $APP_NAME-node-0-production-testing
                      - $APP_NAME-node-1-production-testing
                      - $APP_NAME-node-2-production-testing
              topologyKey: "kubernetes.io/hostname"
  strategy:
    type: Recreate
