apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME-node-1-sandbox
  namespace: chain-sandbox
spec:
  ports:
  - name: ws
    port: 8545
    targetPort: 8545
    protocol: TCP
  - name: https
    port: 1317
    targetPort: 1317
    protocol: TCP
  - name: tcp
    port: 26656
    targetPort: 26656
    protocol: TCP
  selector:
    app: $APP_NAME-node-1-sandbox
  sessionAffinity: None
#  type: NodePort
  type: ClusterIP
